version: '3'
services:
  kanban-laravel:
    build: .
    container_name: kanban-laravel
    volumes:
      - ./src:/app

  kanban-web:
    image: nginx
    container_name: kanban-web
    depends_on:
      - kanban-laravel
    environment:
      - NGINX_SERVER_NAME=_
      - NGINX_PORT=8000
      - NGINX_MAX_BODY=100M
    command: /bin/bash -c "envsubst \"`for v in $$(compgen -v);do printf '$${%s} ' $$v;done`'\" < /etc/nginx/conf.d/vhost.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 8000:8000
    volumes:
      - ./src:/app
      - ./configs/vhost.template:/etc/nginx/conf.d/vhost.template

  kanban-db:
    image: mariadb:10.2
    container_name: kanban-db
    environment:
      MYSQL_DATABASE: kanban
      MYSQL_USER: laravel
      MYSQL_PASSWORD: p455w0rd
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - kanbanmariadbdata:/var/lib/mysql

  kanban-testing-db:
    image: mariadb:10.2
    container_name: kanban-testing-db
    environment:
      MYSQL_DATABASE: kanban-testing
      MYSQL_USER: laravel
      MYSQL_PASSWORD: p455w0rd
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - kanbantestmariadbdata:/var/lib/mysql

volumes:
  kanbanmariadbdata:
  kanbantestmariadbdata:
